name: example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  new_flutter_icons:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

new_flutter_icons:
  includes:
    - ant
    - ent
    - evi
    - fea
    - faw
    - faw5
    - faw5s
    - faw5b
    - fou
    - ion
    - mco
    - mdi
    - oct
    - sli
    - zoc
    - wea

flutter:
  uses-material-design: true
