import 'package:flutter/material.dart';
import '../new_flutter_icon_data.dart';

/// all icons under Evil Icons
///
/// https://evil-icons.io/
abstract class EvilIcons {
  static const IconData archive = NewFlutterIconData.evilIcons(61696);
  static const IconData arrow_down = NewFlutterIconData.evilIcons(61697);
  static const IconData arrow_left = NewFlutterIconData.evilIcons(61698);
  static const IconData arrow_right = NewFlutterIconData.evilIcons(61699);
  static const IconData arrow_up = NewFlutterIconData.evilIcons(61700);
  static const IconData bell = NewFlutterIconData.evilIcons(61701);
  static const IconData calendar = NewFlutterIconData.evilIcons(61702);
  static const IconData camera = NewFlutterIconData.evilIcons(61703);
  static const IconData cart = NewFlutterIconData.evilIcons(61704);
  static const IconData chart = NewFlutterIconData.evilIcons(61705);
  static const IconData check = NewFlutterIconData.evilIcons(61706);
  static const IconData chevron_down = NewFlutterIconData.evilIcons(61707);
  static const IconData chevron_left = NewFlutterIconData.evilIcons(61708);
  static const IconData chevron_right = NewFlutterIconData.evilIcons(61709);
  static const IconData chevron_up = NewFlutterIconData.evilIcons(61710);
  static const IconData clock = NewFlutterIconData.evilIcons(61711);
  static const IconData close = NewFlutterIconData.evilIcons(61712);
  static const IconData close_o = NewFlutterIconData.evilIcons(61713);
  static const IconData comment = NewFlutterIconData.evilIcons(61714);
  static const IconData credit_card = NewFlutterIconData.evilIcons(61715);
  static const IconData envelope = NewFlutterIconData.evilIcons(61716);
  static const IconData exclamation = NewFlutterIconData.evilIcons(61717);
  static const IconData external_link = NewFlutterIconData.evilIcons(61718);
  static const IconData eye = NewFlutterIconData.evilIcons(61719);
  static const IconData gear = NewFlutterIconData.evilIcons(61720);
  static const IconData heart = NewFlutterIconData.evilIcons(61721);
  static const IconData image = NewFlutterIconData.evilIcons(61722);
  static const IconData like = NewFlutterIconData.evilIcons(61723);
  static const IconData link = NewFlutterIconData.evilIcons(61724);
  static const IconData location = NewFlutterIconData.evilIcons(61725);
  static const IconData lock = NewFlutterIconData.evilIcons(61726);
  static const IconData minus = NewFlutterIconData.evilIcons(61727);
  static const IconData navicon = NewFlutterIconData.evilIcons(61728);
  static const IconData paperclip = NewFlutterIconData.evilIcons(61729);
  static const IconData pencil = NewFlutterIconData.evilIcons(61730);
  static const IconData play = NewFlutterIconData.evilIcons(61731);
  static const IconData plus = NewFlutterIconData.evilIcons(61732);
  static const IconData pointer = NewFlutterIconData.evilIcons(61733);
  static const IconData question = NewFlutterIconData.evilIcons(61734);
  static const IconData redo = NewFlutterIconData.evilIcons(61735);
  static const IconData refresh = NewFlutterIconData.evilIcons(61736);
  static const IconData retweet = NewFlutterIconData.evilIcons(61737);
  static const IconData sc_facebook = NewFlutterIconData.evilIcons(61738);
  static const IconData sc_github = NewFlutterIconData.evilIcons(61739);
  static const IconData sc_google_plus = NewFlutterIconData.evilIcons(61740);
  static const IconData sc_instagram = NewFlutterIconData.evilIcons(61741);
  static const IconData sc_linkedin = NewFlutterIconData.evilIcons(61742);
  static const IconData sc_odnoklassniki = NewFlutterIconData.evilIcons(61743);
  static const IconData sc_pinterest = NewFlutterIconData.evilIcons(61744);
  static const IconData sc_skype = NewFlutterIconData.evilIcons(61745);
  static const IconData sc_soundcloud = NewFlutterIconData.evilIcons(61746);
  static const IconData sc_telegram = NewFlutterIconData.evilIcons(61747);
  static const IconData sc_tumblr = NewFlutterIconData.evilIcons(61748);
  static const IconData sc_twitter = NewFlutterIconData.evilIcons(61749);
  static const IconData sc_vimeo = NewFlutterIconData.evilIcons(61750);
  static const IconData sc_vk = NewFlutterIconData.evilIcons(61751);
  static const IconData sc_youtube = NewFlutterIconData.evilIcons(61752);
  static const IconData search = NewFlutterIconData.evilIcons(61753);
  static const IconData share_apple = NewFlutterIconData.evilIcons(61754);
  static const IconData share_google = NewFlutterIconData.evilIcons(61755);
  static const IconData spinner = NewFlutterIconData.evilIcons(61756);
  static const IconData spinner_2 = NewFlutterIconData.evilIcons(61757);
  static const IconData spinner_3 = NewFlutterIconData.evilIcons(61758);
  static const IconData star = NewFlutterIconData.evilIcons(61759);
  static const IconData tag = NewFlutterIconData.evilIcons(61760);
  static const IconData trash = NewFlutterIconData.evilIcons(61761);
  static const IconData trophy = NewFlutterIconData.evilIcons(61762);
  static const IconData undo = NewFlutterIconData.evilIcons(61763);
  static const IconData unlock = NewFlutterIconData.evilIcons(61764);
  static const IconData user = NewFlutterIconData.evilIcons(61765);
}
